Data extension
tbaranes/SwiftyUtils pull request #113
Opened 2019-02-14 08:35 UTC by mredig

added a data extension with a convenient initializer and a couple methods of converting data to other types

2019-02-14 13:02 UTC, tbaranes requested changes
I let you some comments, I know It's code style related meaning it's discutable, but I'm trying (I probably miss some cases) to keep a common style to the library :)

2019-02-14 13:02 UTC, tbaranes commented on Sources/Extensions/DataExtension.swift
> +        guard noSpaces.count % 2 == 0 else { print("invalid hex string: uneven character count"); return nil }
Can you remove the print and move the return on a second line?

2019-02-14 13:02 UTC, tbaranes commented on Sources/Extensions/DataExtension.swift
> +            guard let byte = UInt8(substringByte, radix: 16) else { print("could not convert substring '\(substringByte)' to byte"); return nil }
Same as first above

2019-02-14 13:02 UTC, tbaranes commented on Sources/Extensions/DataExtension.swift
> +            guard substringByte != "0x" else { continue }
Can you move the return on a second line?

2019-02-14 13:02 UTC, tbaranes commented on Sources/Extensions/DataExtension.swift
> +    private func toBytesArray() -> [UInt8] {
Why making a method instead of keeping the implementation inside the declaration? Doesn't seem to be used elsewhere

2019-02-14 13:02 UTC, tbaranes commented on SwiftyUtils/Tests/Extensions/DataExtensionTests.swift
> +
Can you remove that last newline?

2019-02-14 13:02 UTC, tbaranes commented on SwiftyUtils/Tests/Extensions/DataExtensionTests.swift
> +            guard let data = Data(hexString: hexString) else {XCTFail("Couldn't make data out of provided string"); return}
Same as above

2019-02-14 13:02 UTC, tbaranes commented on SwiftyUtils/Tests/Extensions/DataExtensionTests.swift
> +            guard let string = String(data: data, encoding: .utf8) else {XCTFail("Couldn't make string out of data"); return}
Same as above

2019-02-14 13:02 UTC, tbaranes commented on SwiftyUtils/Tests/Extensions/DataExtensionTests.swift
> +            guard let data = Data(hexString: hexString) else {XCTFail("Couldn't make data out of provided string"); return}
Can you move the guard body return to a newline?

2019-02-14 13:02 UTC, tbaranes commented on SwiftyUtils/Tests/Extensions/DataExtensionTests.swift
> +            guard let data = Data(hexString: hexString) else {XCTFail("Couldn't make data out of provided string"); return}
Same as above

2019-02-14 19:57 UTC, mredig commented
happy to do the changes - will follow up soon.

2019-02-14 20:09 UTC, mredig commented
(And I'm not disputing the requests, just sharing my thoughts/why I did things the way I did)

I prefer to keep guard statements on a single line if they are exceedingly simple. (print/return is essentially the same as fatalError(message)) as it's less of an interruption to code flow. If they do anything more complex (like cleanup/etc) I definitely make them take the space needed to keep them easy to read what they do.

The extra newlines are just a trigger happy finger habit I have. I apologize for making extra work on your end, but they are quite invisible to my perception until pointed out. 

All that said, I understand the value of maintaining a common style throughout a project. Just wanted to share. :) I'll be making the changes shortly.

2019-02-18 04:30 UTC, mredig commented on Sources/Extensions/DataExtension.swift
> +    private func toBytesArray() -> [UInt8] {
It's a bit easier for me to read and understand this way, but it doesn't make a huge difference, so I'd be happy to change.

2019-02-18 08:10 UTC, tbaranes approved these changes

2019-02-18 08:10 UTC, merged