Added UIView, NSView and CGRect extensions
tbaranes/SwiftyUtils pull request #38
Opened 2017-01-12 07:03 UTC by Sweeper777

I added some things that make dealing with positions and sizes easier. e.g. you can easily change a view's position by setting its `x` and `y` properties.

2017-01-12 07:13 UTC, tbaranes requested changes
Looks good! I let you a few comments about the README, otherwise that's a cool add 👍

2017-01-12 07:13 UTC, tbaranes commented on README.md
> +let rectAtAnotherPosition = rect.with(x: 100).with(y: 200)
Can you add a comment `// result printed once changed` for each of them?

2017-01-12 07:13 UTC, tbaranes commented on README.md
>  It will iterate on all the subviews of the view, and use the text / placeholder as key in `NSLocalizedString`.
That comment must be below `Automates your localizables` and above the new section.

2017-01-12 07:13 UTC, tbaranes commented on README.md
> +aView.x += 100 // move  to right
Can you add a `var aView: UIView` to make the example more concrete?

2017-01-12 07:13 UTC, tbaranes commented on README.md
> +aView.x += 100 // move  to right
Can you add a `var aView: NSView` to make the example more concrete?

2017-01-12 07:13 UTC, tbaranes commented on README.md
>  It will iterate on all the subviews of the view, and use the text / placeholder as key in `NSLocalizedString`.
Same here: that comment is for the above section / example

2017-01-12 07:14 UTC, tbaranes commented on CHANGELOG.md
> +public func with(height: CGFloat) -> CGRect
Should we have a `func with(origin: CGPoint) -> CGRect` and `func with(size: CGSize) -> CGRect` or is that too much?

2017-01-12 07:21 UTC, Sweeper777 commented on README.md
> +let rectAtAnotherPosition = rect.with(x: 100).with(y: 200)
What do you mean by "result printed once changed"? I didn't have any print statements.

2017-01-12 07:24 UTC, Sweeper777 commented on CHANGELOG.md
> +public func with(height: CGFloat) -> CGRect
Yeah, that's a good idea! I didn't think of that.

2017-01-12 07:26 UTC, tbaranes commented on README.md
> +let rectAtAnotherPosition = rect.with(x: 100).with(y: 200)
For example:
`let widerRect = rect.with(width: 100) // x: 10, y: 20, width: 130, height: 140`

2017-01-12 07:42 UTC, tbaranes commented
Also, can you add some tests? It's straight forward, should never fail, but we are never careful enough!

2017-01-12 07:44 UTC, Sweeper777 commented
Ok. I forgot about them!

2017-01-12 08:13 UTC, Sweeper777 commented
I have added everything (hopefully)! Can this merge?

2017-01-12 08:20 UTC, tbaranes requested changes
I have a last request changes: can you duplicate the `UIViewExtensionsTests` for macOS as well?

2017-01-12 08:27 UTC, Sweeper777 commented
Done!

2017-01-12 08:29 UTC, tbaranes approved these changes
Perfect! Feel free to merge it once travis is green 🎉
Thanks for that PR!

2017-01-12 08:34 UTC, tbaranes commented
There's a few [SwiftLint](https://github.com/realm/SwiftLint) `violations` about names. 
Can you add the following lines to `.swiftlint.yml` (that will fix the name violation):

```
variable_name:
  min_length: 2
  excluded: 
   - x
   - y
```

2017-01-12 08:47 UTC, Sweeper777 commented
Is .swiftlint.yml a file I have to create? I can't find it in the repo.

2017-01-12 08:53 UTC, tbaranes commented
The configuration file for the core is there: `./SwiftyUtils/.swiftlint.yml`
For the example, it's there (no need to change this one, just for your information):  `./SwiftyUtils Example/.swiftlint.yml`

2017-01-12 12:23 UTC, tbaranes commented
I went ahead and fix it (+ bump a few others warnings due to the latest release) in #39 
That was a work I have to do since a few time, so...

You will just have to rebase your PR once I merged the other, then, everything should be ok.

2017-01-12 13:10 UTC, Sweeper777 commented
Do you mean that once #39 is merged, I can press the bottom button there? Is that what rebase means?
<img width="323" alt="screen shot 2017-01-12 at 1 10 54 pm" src="https://cloud.githubusercontent.com/assets/13585047/21890989/7c449836-d8c8-11e6-952d-2e702d42e693.png">

2017-01-12 13:50 UTC, tbaranes commented
We have to ensure firs that travis is passing as expected (should be no issue there), but in order to test  that, you have to rebase without merging, which means pull the lasts commits from master in your branch.

If you are using a terminal:

```
git fetch origin            # Updates origin/master
git rebase origin/master    # Rebases current branch onto origin/master
```

If you are using an application (tower, source tree...), they have generally an option build in to do it.

Let me know if you need more information!

2017-01-12 13:56 UTC, Sweeper777 commented
Ok, seems easy. I'll do that once I get back!

2017-01-12 15:58 UTC, Sweeper777 commented
It is telling me that `git -f push` has an unknown option `-f`. Should it be `git push -f` instead?

2017-01-12 16:05 UTC, tbaranes commented
Yeah, should be that, my bad

2017-01-12 16:07 UTC, tbaranes commented
All good 👍 Feel free to merge that PR once travis is done.
Good job here, thanks!

2017-01-12 17:06 UTC, tbaranes commented
Seems to be there an issue left:

>  ❌  /Users/travis/build/tbaranes/SwiftyUtils/SwiftyUtils/SwiftyUtils macOS Tests/NSViewExtensionsTest.swift:14:20: use of unresolved identifier 'NSView'

`NSViewExtensionsTest.swift` should target only macOS, seems to be currently iOS too

2017-01-12 17:20 UTC, Sweeper777 commented
I think I fixed it. I built the target and ran the test. They all succeeded so it should be alright. Right?

2017-01-12 17:22 UTC, tbaranes commented
Travis will tell us soon enough 😬
But yeah, if it passes in local, it should be ok for travis

2017-01-12 17:43 UTC, tbaranes commented
@Sweeper777 Side note for the next time (I pushed directly in your branch this time):
- Classes added in the Core must target tvOS and watchOS as well (same for the CoreTests)
- When adding a new section in the README, you have to update the summary as well. Also, the README is sorted alphabetically

Otherwise 💯

2017-01-12 18:15 UTC, Sweeper777 commented
Is it normal for Travis to take so long? Is something wrong?

2017-01-12 18:32 UTC, tbaranes commented
It can, that's depending how many build Travis is handling at the same time, and their structures status. Sometimes it's quite long...

2017-01-13 06:11 UTC, merged

2017-01-13 06:13 UTC, Sweeper777 commented
Oops! I was on my phone and I accidentally merged it! I'm so sorry! Travis seems to still fail saying that tests failed.

2017-01-13 07:02 UTC, tbaranes commented
The build failed of travis wasn't due to test but a timeout, it happened, the only solution in this case is to start again the build which has failed. I think you have the rights to do that since you are a contributor. 

For the next time if there's really a test which has failed and a PR is accidentally merged, the good move is just to rollback to the last master commit before the merge, you can find the command line on SO.

For now, it's all good 👍

2017-01-14 11:47 UTC, Sweeper777 commented
Maybe update to 0.7.0 now?

2017-01-14 12:45 UTC, tbaranes commented
👌Will do it this weekend or next week