Preparing 1.0 release
tbaranes/SwiftyUtils pull request #89
Opened 2017-04-14 07:39 UTC by tbaranes

Closing #52

2017-04-14 19:50 UTC, Sweeper777 requested changes

2017-04-14 19:50 UTC, Sweeper777 commented on CHANGELOG.md
> +A big thanks to [Mulang Su](https://github.com/Sweeper777) for reviewing all the PRs!
Can you use "Sweepr777" here instead? I prefer this name.

2017-04-14 20:29 UTC, Sweeper777 commented on CHANGELOG.md
> +A big thanks to [Mulang Su](https://github.com/Sweeper777) for reviewing all the PRs!
Thanks for giving me credit!

2017-04-16 17:47 UTC, tbaranes commented
@Sweeper777 Credits updated!

2017-04-16 17:48 UTC, Sweeper777 approved these changes

2017-04-16 18:03 UTC, merged